[phases.setup]
nixpacks.pkgs = ["python3"]

[phases.build]
commands = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn main:app"

# Tambahkan baris ini untuk menentukan direktori aplikasi Anda
nixpacks.app_dir = "app"