[phases.setup]
nixpacks.base_image = "python:3.9"
nixpacks.pkgs = ["python3", "python3-pip"]

[phases.build]
commands = [
  "/usr/local/bin/python3 -m ensurepip --upgrade",
  "/usr/local/bin/python3 -m pip install --upgrade pip",
  "/usr/local/bin/pip3 install -r requirements.txt"
]

[start]
cmd = "gunicorn main:app"

# Tentukan direktori aplikasi
nixpacks.app_dir = "app"