nixpacks.app_dir = "app"

[phases.setup]
nixpacks.pkgs = ["python3", "pip"]

[phases.build]
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn main:app"

# Tentukan direktori aplikasi
